# Source: Genesis/charts/bdlstudio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3rd-party-app-cifar10
  labels:
    app: 3rd-party-app-cifar10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3rd-party-app-cifar10
  template:
    metadata:
      labels:
        app: 3rd-party-app-cifar10
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: 3rd-party-app-cifar10
        image: swa/3rd_party_application/cifar10:v1.0
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 500Mi
