apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: cifa-10
  namespace: myspace
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  default:
    predictor:
      serviceAccountName: kfserving-sa
      tensorflow:
        storageUri: 's3://model/cifa10/'
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi