# Source: Genesis/charts/bdlstudio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing
  labels:
    app: data-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-processing
  template:
    metadata:
      labels:
        app: data-processing
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: data-processing
        image: swa/data_processing/cifar10:v1.0
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 500Mi
