# Source: Genesis/charts/bdlstudio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-source
  labels:
    app: data-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-source
  template:
    metadata:
      labels:
        app: data-source
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: data-source
        image: swa/data_source/cifar10:v1.0
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 500Mi
